### PR TITLE
Changed exceptions to specialized on.

### PR DESCRIPTION
**Pull request by Pigotka**
HA will not allow me to catch broad exception. I needed to specialize  to solve the warning:
W0703: Catching too general exception Exception (broad-except)

### CODE REVIEW

**Comment by fdegier** [comment]
Makes sense, could you remove the `__pycache__` folder from your commit?

**Comment by Pigotka** [comment]
Done. Sorry about that, I'm new with git.

**Comment by fdegier** [comment]
No worries, thank you for your contribution!

**Review by fdegier — APPROVED** [review]
LGTM

**Comment by fdegier** [comment]
BTW, looking forward to your plugin for HA.

**Comment by Pigotka** [comment]
@fdegier can you fix publish action so package gets uploaded to pipy please?

**Comment by fdegier** [comment]
Hey, it is available https://pypi.org/project/JablotronPy/0.2.1/#history

I just noticed I made an earlier incorrect version which is actually higher. I'll publish a new release to sort that out.

**Comment by Pigotka** [comment]
Oh that explains it. Thanks.

**Pull request merged**
